[package]
name = "varlink"
version = "0.8.1"
authors = ["Harald Hoyer <harald@redhat.com>"]
license = "MIT/Apache-2.0"
documentation = "https://github.com/varlink/rust/blob/master/varlink/README.md"
homepage = "https://github.com/varlink/rust/blob/master/varlink"
repository = "https://github.com/varlink/rust"
description = "Client and server support for the varlink protocol."
readme = "README.md"

keywords = ["varlink", "ipc", "rpc", "protocol"]
categories = ["os", "development-tools", "network-programming"]

[lib]
name = "varlink"
path = "src/lib.rs"

[[bin]]
name = "varlink-rust-generator"
path = "src/bin/varlink-rust-generator.rs"

[dependencies]
libc = "0"
unix_socket = "0.5.0"
itertools = "0"
serde = "1"
serde_derive = "1"
serde_json = "1"
bytes = "0"
tempfile = "3"
failure_derive = "0.1.1"
failure = "0.1.1"
varlink_parser = { version = "0.8", path = "../varlink_parser" }

[badges]
travis-ci = { repository = "varlink/rust" }
coveralls = { repository = "varlink/rust", branch = "master", service = "github" }

[dev-dependencies]
varlink_parser = { version = "0", path = "../varlink_parser" }
