[package]
name = "varlink_parser"
version = "0.8.1"
authors = ["Harald Hoyer <harald@redhat.com>"]
build = "build.rs"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/varlink_parser/"
homepage = "https://github.com/varlink/rust"
repository = "https://github.com/varlink/rust"
description = "A crate for parsing varlink interface definition files."
readme = "README.md"

keywords = ["parser", "varlink", "ipc", "rpc", "protocol"]
categories = ["parsing", "development-tools"]

[badges]
travis-ci = { repository = "varlink/rust" }

[dependencies]
itertools = "0"
bytes = "0"
failure_derive = "0.1.1"
failure = "0.1.1"

[build-dependencies]
peg = "0.5"

